/* pointers to token semantic values for bww2tex
   version 2.0
   by Walt Innes {walt@slac.stanford.edu)
*/
extern char *reprmorceau;
extern char *suspmorceau;
extern char *xbarre;
extern char *leftrepeatsymbol;
extern char *alaligne;
extern char *setdoublebar;
extern char *setrightrepeat;
extern char *doublebar;
extern char *itenu;
extern char *tten;
extern char *triolet;
extern char *meterC;
extern char *allabreve;
extern char *first;
extern char *second;
extern char *sing;
extern char *doub;
extern char *bis;
extern char *endfs;
extern char *signature;
extern char *realwide;

extern char *N ;
extern char *a ;
extern char *b ;
extern char *c ;
extern char *d ;
extern char *e ;
extern char *f ;
extern char *g ;
extern char *hh ;

extern char *wh ;
extern char *ql ;
extern char *s  ;
extern char *t  ;
extern char *sf ;

extern char *r  ;
extern char *l  ;

extern char *gra;
extern char *grb;
extern char *grc;
extern char *grd;
extern char *gre;
extern char *grf;
extern char *grg;
extern char *grh;

extern char *gr ;
extern char *echo;
extern char *them;
extern char *ddgr;
extern char *edgr;
extern char *fdgr;
extern char *gdgr;
extern char *tdgr;
extern char *dstr;
extern char *gdstr;
extern char *tdstr;
extern char *hdstr;
extern char *tstr;
extern char *gtstr;
extern char *ttstr;
extern char *htstr;
extern char *dbl;
extern char *tdbl;
extern char *hdbl;
extern char *hslur;
extern char *hshk;
extern char *slur;
extern char *shk;
extern char *tslur;
extern char *tshk;
extern char *pel ;
extern char *lpel ;
extern char *tpel;
extern char *ltpel;
extern char *hpel;
extern char *catch;
extern char *scatch;
extern char *tcatch;

extern char *ldstrd;
extern char *ltstrd;
extern char *thrwd;
extern char *gripthrwd;
extern char *hthrwd;
extern char *hgripthrwd;
extern char *tra;
extern char *trac;
extern char *htra;
extern char *wbirl;
extern char *birl;
extern char *sbirl;
extern char *tbirl;
extern char *grip;
extern char *hgrip;
extern char *dgrip;
extern char *Ngrip;
extern char *deda;
extern char *taor;
extern char *dtaor;
extern char *htaor;
extern char *Ntaor;
extern char *ahtaor;
extern char *ahtaorb;
extern char *crun;
extern char *dcrun;
extern char *ahcrun;
extern char *crunbr;
extern char *dcrunbr;
extern char *hcrunbr;
extern char *ahcrunbr;
extern char *Nhcrun;
extern char *darodo;
extern char *Ndarodo;
extern char *darodos;

extern char *edre;
extern char *edreb;
extern char *edrec;
extern char *edred;
extern char *dare;
extern char *hedari;
extern char *dbstf;
extern char *dbsth;
extern char *gedre;
extern char *gdare;
extern char *tedre;
extern char *tdare;
extern char *tchechere;
extern char *hchechere;
extern char *hdre;
extern char *hedale;
extern char *hiharin;
extern char *chelalho;

extern char *cadged;
extern char *cadge;
extern char *cadgf;
extern char *caded;
extern char *cadaed;
extern char *cadae;
extern char *fcadged;
extern char *fcadge;
extern char *fcadgf;
extern char *fcaded;
extern char *fcadaed;
extern char *fcadae;
extern char *fcade;

extern char *hgrpb;
extern char *hgrpc;
extern char *scatchb;
extern char *scatchc;
extern char *tcatchb;
extern char *tcatchc;

extern char *enbain;
extern char *otro;
extern char *odro;
extern char *adela;
extern char *genbain;
extern char *gotro;
extern char *godro;
extern char *gadela;
extern char *tenbain;
extern char *totro;
extern char *todro;
extern char *tadela;

extern char *pause;
extern char *hpause;
extern char *soupir;
extern char *dsoupir;
extern char *quantsoupir;
extern char *huitsoupir;

extern char *pointdorgue;
extern char *fermat;
extern char *pince;
extern char *pdare;
extern char *trille;
extern char *turn;
extern char *upz;
extern char *abrleum;
extern char *abrleumbr;
extern char *abrtaor;
extern char *abrtaorbr;
extern char *abrtaorm;
extern char *abrcrun;
extern char *abrcrunbr;
extern char *abrcrunm;
extern char *abrtrip;

extern char *na;
extern char *fl;
extern char *shp;

extern char *fine;
extern char *segno;
extern char *dalsegno;
extern char *coda;
extern char *dacapoalfine;
extern char *dacapoalcoda;

extern char *one;
extern char *two;
